= Magnetometer Library
This library provides an interface to the FXOS8700CQ magnetometer for Arduino-compatible boards.

== Installation
To install this library:

1. Download the library.
2. Extract the contents to the `libraries` folder of your Arduino IDE.
3. Restart the Arduino IDE.

== Usage
Include the library in your sketch and create an instance of the `Magnetometer` class.

== Examples
The library comes with example sketches to help you get started. Check the examples folder for more information.

== API Reference

Initializes the magnetometer with specified I2C pins and rate.
void begin(uint8_t i2cPins = I2C_PINS_18_19, uint32_t i2cRate = I2C_RATE_400);

Updates the magnetometer data.
void update();

Returns the X-axis magnetic field value.
float getX();

Returns the Y-axis magnetic field value.
float getY();

Returns the Z-axis magnetic field value.
float getZ();

Calibrates the magnetometer.
void calibrate();

== License
This library is licensed under the MIT License.
